import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import React, {useEffect, useState} from "react";
import {io} from "socket.io-client";
import Profile from "@/components/profile";

const inter = Inter({ subsets: ['latin'] })

let socket;
export default function Home() {

    // useEffect(() => {
    //     socketInitializer();
    // }, []);
    //
    // const socketInitializer = async () => {
    //     // We just call it because we don't need anything else out of it
    //     await fetch("/api/socket");
    //
    //     socket = io();
    //
    //     socket.on("newIncomingMessage", (message) => {
    //         console.log("client: " + message);
    //     });
    // };


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>
                    <button onClick={() => {fetch("/api/test")}}>Click me</button>
                </div>
                {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
                <a href="/api/auth/login">Login</a>
                {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
                <a href="/api/auth/logout">Logout</a>

                <Profile />
            </main>
        </>
    )
}
